### ISSUE TITLE
analyze-hack.js Breaks on launch 

### ISSUE THREAD

**Issue by arcad3luke** [alainbryden/bitburner-scripts#193]
Hey, so  I tried to run the` autopilot.js `file, and it crashed while trying to start `daemon.js.` The call stack printed:
`RUNTIME ERROR
analyze-hack.js@home (PID - 87491)
Args: ["--all", "--silent"]

Cannot read properties of undefined (reading 'hostname')
stack:
TypeError: Cannot read properties of undefined (reading 'hostname')
at Module.main (home/analyze-hack.js:143:60)
at executeJSScript (file:///S:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:119700)`
After checking the `analyze-hack.js` script, I found:
`    let serverListByExp = `Servers in order of best to worst hack exp at Hack ${player.hacking}:`;
    for (let i = 0; i < 5; i++)
        serverListByExp += `\n ${order++} ${server_eval[i].hostname}, with ${server_eval[i].expRate.toPrecision(3)} exp per ram-second`;
        
    ns.print(serverListByExp);
    `
is there a set of curly braces missing, or is that something I missed when learning js about for loops?

**Comment by arcad3luke** [comment]
Removing after seeing #184.
