### ISSUE TITLE
Daemon breaks on Launch

### ISSUE THREAD

**Issue by arcad3luke** [alainbryden/bitburner-scripts#194]
Hey, I got this error at the same time as #193.

WARNING: daemon.js Caught an error in the targeting loop: Cannot read properties of undefined (reading 'timeToHack')
TypeError: Cannot read properties of undefined (reading 'timeToHack')
    at doTargetingLoop (home/daemon.js:692:60)
    at async Module.main (home/daemon.js:336:5)`
When checking the file and lines:
`let expectedRunTime = getBestXPFarmTarget().timeToHack();` (home/daemon.js:692:60)
and
`await doTargetingLoop(ns);`(home/daemon.js:336:5)
after checking `doTargetingLoop`, I noticed this:
`usedRam() { return this.ns.getServerUsedRam(this.name); }
ramAvailable() { return this.totalRam() - this.usedRam(); }
growDelay() { return this.timeToWeaken() - this.timeToGrow() + cycleTimingDelay; }
hackDelay() { return this.timeToWeaken() - this.timeToHack(); }
timeToWeaken() { return this.ns.getWeakenTime(this.name); }
timeToGrow() { return this.ns.getGrowTime(this.name); }
timeToHack() { return this.ns.getHackTime(this.name); }` (home/daemon.js:934-940)

Would this cause the undefined error, considering the timeToHack(), timetoWeaken(), and timeToGrow() declarations are after the calls for them?

**Comment by arcad3luke** [comment]
Removing after seeing #184
