### ISSUE TITLE
Update for 2.2.0?

### ISSUE THREAD

**Issue by kotenok2000** [alainbryden/bitburner-scripts#250]

**Comment by mcxerxes82** [comment]
FAIL: Attempt 5 of 5 failed: 
ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/ps-other-instances.txt.js",1,"home","gangs.js");

**Comment by alainbryden** [comment]
I'll probably poke away at these backwards-incompatible changes later this
week. Feel free to drop any findings here.

**Comment by ashugar** [comment]
I believe this is from the autopilot.js script.

Per the Update notes, the following needs to change:
Line 637:
`const pid = ns.run(convertFileName ? getFilePath(baseScriptName) : baseScriptName, 1, ...args);`

Change to the following by adding a const:
`	const run = ns.run.bind(ns); // V2.2 update
	const pid = run(convertFileName ? getFilePath(baseScriptName) : baseScriptName, 1, ...args);`

**Comment by MaKeG0** [comment]
Hello, I'm using your bundle with some very light tweaks and those are the errors I'm getting after running autopilot.
Hope it will be helpfull
```
RUNTIME ERROR
analyze-hack.js@home (PID - 74)


ns.getServer called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const getServer = ns.getServer.bind(ns);
getServer("home",0,["home","hacknet-node-8","hacknet-node-7","hacknet-node-6","hacknet-node-5","hacknet-node-4","hacknet-node-3","hacknet-node-2","hacknet-node-1","hacknet-node-0","darkweb","iron-gym","harakiri-sushi","CSEC","omega-net","computek","I.I.I.I","aevum-police","alpha-ent","rho-construction","snap-fitness","aerocorp","unitalife","solaris","defcomm","infocomm","applied-energetics","fulcrumtech","4sigma","clarkinc","ecorp","blade","b-and-a","The-Cave","fulcrumassets","omnia","zeus-med","univ-energy","nova-med","run4theh111z","stormtech","kuai-gong","microdyne","vitalife","helios",".","omnitek","powerhouse-fitness","nwo","megacorp","zb-def","icarus","taiyang-digital","titan-labs","catalyst","silver-helix","johnson-ortho","syscore","lexo-corp","global-pharm","galactic-cyber","deltaone","the-hub","summit-uni","zer0","hong-fang-tea","joesguns","sigma-cosmetics","max-hardware","neo-net","avmnite-02h","foodnstuff","n00dles","nectar-net","phantasy","crush-fitness","rothman-uni","netlink","zb-institute","millenium-fitness"]);


stack:
Error: 
ns.getServer called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const getServer = ns.getServer.bind(ns);
getServer("home",0,["home","hacknet-node-8","hacknet-node-7","hacknet-node-6","hacknet-node-5","hacknet-node-4","hacknet-node-3","hacknet-node-2","hacknet-node-1","hacknet-node-0","darkweb","iron-gym","harakiri-sushi","CSEC","omega-net","computek","I.I.I.I","aevum-police","alpha-ent","rho-construction","snap-fitness","aerocorp","unitalife","solaris","defcomm","infocomm","applied-energetics","fulcrumtech","4sigma","clarkinc","ecorp","blade","b-and-a","The-Cave","fulcrumassets","omnia","zeus-med","univ-energy","nova-med","run4theh111z","stormtech","kuai-gong","microdyne","vitalife","helios",".","omnitek","powerhouse-fitness","nwo","megacorp","zb-def","icarus","taiyang-digital","titan-labs","catalyst","silver-helix","johnson-ortho","syscore","lexo-corp","global-pharm","galactic-cyber","deltaone","the-hub","summit-uni","zer0","hong-fang-tea","joesguns","sigma-cosmetics","max-hardware","neo-net","avmnite-02h","foodnstuff","n00dles","nectar-net","phantasy","crush-fitness","rothman-uni","netlink","zb-institute","millenium-fitness"]);
```
```
RUNTIME ERROR
stats.js@home (PID - 81)


ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/ps-other-instances.txt.js",1,"home","stats.js");


stack:
Error: 
ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/ps-other-instances.txt.js",1,"home","stats.js");


    at value (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:251572)
    at home/helpers.js:249:16
    at autoRetry (home/helpers.js:312:34)
    at async runCommand_Custom (home/helpers.js:235:12)
    at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
    at async getNsDataThroughFile (home/helpers.js:137:12)
    at async instanceCount (home/helpers.js:412:20)
    at async Module.main (home/stats.js:20:21)
    at async M (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:272755)
```

```
RUNTIME ERROR
stockmaster.js@home (PID - 82)


ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/hasTIX.txt.js",1);


stack:
Error: 
ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/hasTIX.txt.js",1);


    at value (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:251572)
    at home/helpers.js:249:16
    at autoRetry (home/helpers.js:312:34)
    at async runCommand_Custom (home/helpers.js:235:12)
    at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
    at async getNsDataThroughFile (home/helpers.js:137:12)
    at async Module.main (home/stockmaster.js:76:29)
    at async M (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:272755)
```

```
RUNTIME ERROR
sleeve.js@home (PID - 83)


ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/ps-other-instances.txt.js",1,"home","sleeve.js");


stack:
Error: 
ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/ps-other-instances.txt.js",1,"home","sleeve.js");


    at value (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:251572)
    at home/helpers.js:249:16
    at autoRetry (home/helpers.js:312:34)
    at async runCommand_Custom (home/helpers.js:235:12)
    at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
    at async getNsDataThroughFile (home/helpers.js:137:12)
    at async instanceCount (home/helpers.js:412:20)
    at async Module.main (home/sleeve.js:52:24)
    at async M (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:272755)
```

```
RUNTIME ERROR
/Tasks/contractor.js@home (PID - 84)


ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/contract-types.txt.js",1,"[{\"contract\":\"contract-728898.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-775410.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-842147.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-183163.cct\",\"hostname\":\"aevum-police\"},{\"contract\":\"contract-296272.cct\",\"hostname\":\"snap-fitness\"},{\"contract\":\"contract-803600-CyberSec.cct\",\"hostname\":\"solaris\"},{\"contract\":\"contract-150651.cct\",\"hostname\":\"infocomm\"},{\"contract\":\"contract-115878.cct\",\"hostname\":\"4sigma\"},{\"contract\":\"contract-862151-Aevum.cct\",\"hostname\":\"ecorp\"},{\"contract\":\"contract-551625-Aevum.cct\",\"hostname\":\"zeus-med\"},{\"contract\":\"contract-593661.cct\",\"hostname\":\"zeus-med\"},{\"contract\":\"contract-350165-Netburners.cct\",\"hostname\":\"nova-med\"},{\"contract\":\"contract-530964.cct\",\"hostname\":\"nova-med\"},{\"contract\":\"contract-474310.cct\",\"hostname\":\"vitalife\"},{\"contract\":\"contract-121638.cct\",\"hostname\":\"megacorp\"},{\"contract\":\"contract-765160.cct\",\"hostname\":\"titan-labs\"},{\"contract\":\"contract-440273.cct\",\"hostname\":\"silver-helix\"},{\"contract\":\"contract-329721.cct\",\"hostname\":\"syscore\"},{\"contract\":\"contract-163212-Aevum.cct\",\"hostname\":\"galactic-cyber\"},{\"contract\":\"contract-537861.cct\",\"hostname\":\"deltaone\"},{\"contract\":\"contract-926290-CyberSec.cct\",\"hostname\":\"summit-uni\"},{\"contract\":\"contract-317349.cct\",\"hostname\":\"zer0\"},{\"contract\":\"contract-375866-CyberSec.cct\",\"hostname\":\"joesguns\"},{\"contract\":\"contract-961115.cct\",\"hostname\":\"max-hardware\"},{\"contract\":\"contract-148373-Aevum.cct\",\"hostname\":\"n00dles\"},{\"contract\":\"contract-273791.cct\",\"hostname\":\"nectar-net\"},{\"contract\":\"contract-506296.cct\",\"hostname\":\"crush-fitness\"},{\"contract\":\"contract-59198-Netburners.cct\",\"hostname\":\"crush-fitness\"},{\"contract\":\"contract-238289.cct\",\"hostname\":\"netlink\"}]");


stack:
Error: 
ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/contract-types.txt.js",1,"[{\"contract\":\"contract-728898.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-775410.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-842147.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-183163.cct\",\"hostname\":\"aevum-police\"},{\"contract\":\"contract-296272.cct\",\"hostname\":\"snap-fitness\"},{\"contract\":\"contract-803600-CyberSec.cct\",\"hostname\":\"solaris\"},{\"contract\":\"contract-150651.cct\",\"hostname\":\"infocomm\"},{\"contract\":\"contract-115878.cct\",\"hostname\":\"4sigma\"},{\"contract\":\"contract-862151-Aevum.cct\",\"hostname\":\"ecorp\"},{\"contract\":\"contract-551625-Aevum.cct\",\"hostname\":\"zeus-med\"},{\"contract\":\"contract-593661.cct\",\"hostname\":\"zeus-med\"},{\"contract\":\"contract-350165-Netburners.cct\",\"hostname\":\"nova-med\"},{\"contract\":\"contract-530964.cct\",\"hostname\":\"nova-med\"},{\"contract\":\"contract-474310.cct\",\"hostname\":\"vitalife\"},{\"contract\":\"contract-121638.cct\",\"hostname\":\"megacorp\"},{\"contract\":\"contract-765160.cct\",\"hostname\":\"titan-labs\"},{\"contract\":\"contract-440273.cct\",\"hostname\":\"silver-helix\"},{\"contract\":\"contract-329721.cct\",\"hostname\":\"syscore\"},{\"contract\":\"contract-163212-Aevum.cct\",\"hostname\":\"galactic-cyber\"},{\"contract\":\"contract-537861.cct\",\"hostname\":\"deltaone\"},{\"contract\":\"contract-926290-CyberSec.cct\",\"hostname\":\"summit-uni\"},{\"contract\":\"contract-317349.cct\",\"hostname\":\"zer0\"},{\"contract\":\"contract-375866-CyberSec.cct\",\"hostname\":\"joesguns\"},{\"contract\":\"contract-961115.cct\",\"hostname\":\"max-hardware\"},{\"contract\":\"contract-148373-Aevum.cct\",\"hostname\":\"n00dles\"},{\"contract\":\"contract-273791.cct\",\"hostname\":\"nectar-net\"},{\"contract\":\"contract-506296.cct\",\"hostname\":\"crush-fitness\"},{\"contract\":\"contract-59198-Netburners.cct\",\"hostname\":\"crush-fitness\"},{\"contract\":\"contract-238289.cct\",\"hostname\":\"netlink\"}]");


    at value (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:251572)
    at home/helpers.js:249:16
    at autoRetry (home/helpers.js:312:34)
    at async runCommand_Custom (home/helpers.js:235:12)
    at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
    at async getNsDataThroughFile (home/helpers.js:137:12)
    at async contractsDictCommand (home//Tasks/contractor.js:20:61)
    at async Module.main (home//Tasks/contractor.js:22:29)
    at async M (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:272755)
```

```
RUNTIME ERROR
/Tasks/ram-manager.js@home (PID - 85)


ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/getServerMoneyAvailable.txt.js",1,"home");


stack:
Error: 
ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/getServerMoneyAvailable.txt.js",1,"home");


    at value (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:251572)
    at home/helpers.js:249:16
    at autoRetry (home/helpers.js:312:34)
    at async runCommand_Custom (home/helpers.js:235:12)
    at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
    at async getNsDataThroughFile (home/helpers.js:137:12)
    at async Module.main (home//Tasks/ram-manager.js:19:19)
    at async M (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:272755)
```

```
RUNTIME ERROR
faction-manager.js@home (PID - 86)


ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/ps-other-instances.txt.js",1,"home","faction-manager.js");


stack:
Error: 
ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/ps-other-instances.txt.js",1,"home","faction-manager.js");


    at value (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:251572)
    at home/helpers.js:249:16
    at autoRetry (home/helpers.js:312:34)
    at async runCommand_Custom (home/helpers.js:235:12)
    at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
    at async getNsDataThroughFile (home/helpers.js:137:12)
    at async instanceCount (home/helpers.js:412:20)
    at async Module.main (home/faction-manager.js:95:24)
    at async M (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:272755)
```
```
RUNTIME ERROR
host-manager.js@home (PID - 202)


ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/ps-other-instances.txt.js",1,"home","host-manager.js");


stack:
Error: 
ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/ps-other-instances.txt.js",1,"home","host-manager.js");


    at value (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:251572)
    at home/helpers.js:249:16
    at autoRetry (home/helpers.js:312:34)
    at async runCommand_Custom (home/helpers.js:235:12)
    at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
    at async getNsDataThroughFile (home/helpers.js:137:12)
    at async instanceCount (home/helpers.js:412:20)
    at async Module.main (home/host-manager.js:40:24)
    at async M (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:272755)
```

```
RUNTIME ERROR
/Tasks/contractor.js@home (PID - 263)


ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/contract-types.txt.js",1,"[{\"contract\":\"contract-728898.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-775410.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-842147.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-183163.cct\",\"hostname\":\"aevum-police\"},{\"contract\":\"contract-296272.cct\",\"hostname\":\"snap-fitness\"},{\"contract\":\"contract-803600-CyberSec.cct\",\"hostname\":\"solaris\"},{\"contract\":\"contract-150651.cct\",\"hostname\":\"infocomm\"},{\"contract\":\"contract-115878.cct\",\"hostname\":\"4sigma\"},{\"contract\":\"contract-862151-Aevum.cct\",\"hostname\":\"ecorp\"},{\"contract\":\"contract-551625-Aevum.cct\",\"hostname\":\"zeus-med\"},{\"contract\":\"contract-593661.cct\",\"hostname\":\"zeus-med\"},{\"contract\":\"contract-350165-Netburners.cct\",\"hostname\":\"nova-med\"},{\"contract\":\"contract-530964.cct\",\"hostname\":\"nova-med\"},{\"contract\":\"contract-474310.cct\",\"hostname\":\"vitalife\"},{\"contract\":\"contract-121638.cct\",\"hostname\":\"megacorp\"},{\"contract\":\"contract-765160.cct\",\"hostname\":\"titan-labs\"},{\"contract\":\"contract-440273.cct\",\"hostname\":\"silver-helix\"},{\"contract\":\"contract-329721.cct\",\"hostname\":\"syscore\"},{\"contract\":\"contract-163212-Aevum.cct\",\"hostname\":\"galactic-cyber\"},{\"contract\":\"contract-537861.cct\",\"hostname\":\"deltaone\"},{\"contract\":\"contract-926290-CyberSec.cct\",\"hostname\":\"summit-uni\"},{\"contract\":\"contract-317349.cct\",\"hostname\":\"zer0\"},{\"contract\":\"contract-375866-CyberSec.cct\",\"hostname\":\"joesguns\"},{\"contract\":\"contract-961115.cct\",\"hostname\":\"max-hardware\"},{\"contract\":\"contract-148373-Aevum.cct\",\"hostname\":\"n00dles\"},{\"contract\":\"contract-273791.cct\",\"hostname\":\"nectar-net\"},{\"contract\":\"contract-506296.cct\",\"hostname\":\"crush-fitness\"},{\"contract\":\"contract-59198-Netburners.cct\",\"hostname\":\"crush-fitness\"},{\"contract\":\"contract-238289.cct\",\"hostname\":\"netlink\"}]");


stack:
Error: 
ns.run called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const run = ns.run.bind(ns);
run("/Temp/contract-types.txt.js",1,"[{\"contract\":\"contract-728898.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-775410.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-842147.cct\",\"hostname\":\"I.I.I.I\"},{\"contract\":\"contract-183163.cct\",\"hostname\":\"aevum-police\"},{\"contract\":\"contract-296272.cct\",\"hostname\":\"snap-fitness\"},{\"contract\":\"contract-803600-CyberSec.cct\",\"hostname\":\"solaris\"},{\"contract\":\"contract-150651.cct\",\"hostname\":\"infocomm\"},{\"contract\":\"contract-115878.cct\",\"hostname\":\"4sigma\"},{\"contract\":\"contract-862151-Aevum.cct\",\"hostname\":\"ecorp\"},{\"contract\":\"contract-551625-Aevum.cct\",\"hostname\":\"zeus-med\"},{\"contract\":\"contract-593661.cct\",\"hostname\":\"zeus-med\"},{\"contract\":\"contract-350165-Netburners.cct\",\"hostname\":\"nova-med\"},{\"contract\":\"contract-530964.cct\",\"hostname\":\"nova-med\"},{\"contract\":\"contract-474310.cct\",\"hostname\":\"vitalife\"},{\"contract\":\"contract-121638.cct\",\"hostname\":\"megacorp\"},{\"contract\":\"contract-765160.cct\",\"hostname\":\"titan-labs\"},{\"contract\":\"contract-440273.cct\",\"hostname\":\"silver-helix\"},{\"contract\":\"contract-329721.cct\",\"hostname\":\"syscore\"},{\"contract\":\"contract-163212-Aevum.cct\",\"hostname\":\"galactic-cyber\"},{\"contract\":\"contract-537861.cct\",\"hostname\":\"deltaone\"},{\"contract\":\"contract-926290-CyberSec.cct\",\"hostname\":\"summit-uni\"},{\"contract\":\"contract-317349.cct\",\"hostname\":\"zer0\"},{\"contract\":\"contract-375866-CyberSec.cct\",\"hostname\":\"joesguns\"},{\"contract\":\"contract-961115.cct\",\"hostname\":\"max-hardware\"},{\"contract\":\"contract-148373-Aevum.cct\",\"hostname\":\"n00dles\"},{\"contract\":\"contract-273791.cct\",\"hostname\":\"nectar-net\"},{\"contract\":\"contract-506296.cct\",\"hostname\":\"crush-fitness\"},{\"contract\":\"contract-59198-Netburners.cct\",\"hostname\":\"crush-fitness\"},{\"contract\":\"contract-238289.cct\",\"hostname\":\"netlink\"}]");


    at value (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:251572)
    at home/helpers.js:249:16
    at autoRetry (home/helpers.js:312:34)
    at async runCommand_Custom (home/helpers.js:235:12)
    at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
    at async getNsDataThroughFile (home/helpers.js:137:12)
    at async contractsDictCommand (home//Tasks/contractor.js:20:61)
    at async Module.main (home//Tasks/contractor.js:22:29)
    at async M (file:///K:/Games/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:272755)
```

**Comment by alainbryden** [comment]
Closing this ticket because all the ns.bind breaks have been fixed by a game update.

I'll open separate tickets for the individual API changes.
