### ISSUE TITLE
Autopilot Warning/Error loops

### ISSUE THREAD

**Issue by mubone2003** [alainbryden/bitburner-scripts#315]

**Comment by mubone2003** [comment]
Pulled latest just before this post and retested - autopilot runs in an error loop trying to start multiple instances of the same scripts. Runs from a subdirectory with no arguments. Casino engages and completes successfully, but the rest error out as below. BN 12.46 - I had been running vanilla autopilot through many BNs. This started just after the 2.3 update

![image](https://github.com/alainbryden/bitburner-scripts/assets/139516304/10d5c51d-7ccc-4a0d-9a07-0451e94467a8)

Bitburner v2.3.1 (100030008)
[2023-07-13 08:53:23.053] alainbryden/casino.js: SUCCESS: We've been kicked out of the casino.
[2023-07-13 08:53:23.053] alainbryden/autopilot.js: INFO: Auto-pilot engaged...
[2023-07-13 08:53:23.053] Accessed deprecated function or property: ns.getPlayer().playtimeSinceLastAug
[2023-07-13 08:53:23.053] This is no longer supported usage and will be removed in a later version.
[2023-07-13 08:53:23.053] Use ns.getResetInfo().lastAugReset instead. This is a static timestamp instead of an elapsed time.
[2023-07-13 08:53:23.053] This message can also appear for object properties when the object's values are iterated.
[2023-07-13 08:53:23.053] This message will only be shown once per game session for each deprecated item accessed.
[2023-07-13 08:53:23.053] Accessed deprecated function or property: ns.getPlayer().playtimeSinceLastBitnode
[2023-07-13 08:53:23.053] This is no longer supported usage and will be removed in a later version.
[2023-07-13 08:53:23.053] Use ns.getResetInfo().lastNodeReset instead. This is a static timestamp instead of an elapsed time.
[2023-07-13 08:53:23.053] This message can also appear for object properties when the object's values are iterated.
[2023-07-13 08:53:23.053] This message will only be shown once per game session for each deprecated item accessed.
[2023-07-13 08:53:23.053] Accessed deprecated function or property: ns.getPlayer().bitNodeN
[2023-07-13 08:53:23.053] This is no longer supported usage and will be removed in a later version.
[2023-07-13 08:53:23.053] Use ns.getResetInfo().currentNode instead
[2023-07-13 08:53:23.053] This message can also appear for object properties when the object's values are iterated.
[2023-07-13 08:53:23.053] This message will only be shown once per game session for each deprecated item accessed.
[2023-07-13 08:53:24.053] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 21) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 08:53:24.053] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 22) with args: [--training-reserve, 300000]
[2023-07-13 08:53:24.053] alainbryden/autopilot.js: INFO: Launched daemon.js (pid: 23) with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 08:53:25.053] Accessed deprecated function or property: ns.nFormat
[2023-07-13 08:53:25.053] This is no longer supported usage and will be removed in a later version.
[2023-07-13 08:53:25.053] Use ns.formatNumber, formatRam, formatPercent, or js builtins like Intl.NumberFormat instead.
[2023-07-13 08:53:25.053] This message can also appear for object properties when the object's values are iterated.
[2023-07-13 08:53:25.053] This message will only be shown once per game session for each deprecated item accessed.
[2023-07-13 08:53:25.053] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:26.053] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:26.053] alainbryden/Tasks/ram-manager.js: SUCCESS: Upgraded home RAM from 128 GB to 256 GB (cost: $250.361m)
[2023-07-13 08:53:26.053] alainbryden/Tasks/ram-manager.js: SUCCESS: Upgraded home RAM from 256 GB to 512 GB (cost: $791.142m)
[2023-07-13 08:53:34.053] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 365) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 08:53:34.053] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 366) with args: []
[2023-07-13 08:53:34.053] alainbryden/autopilot.js: INFO: Launched daemon.js (pid: 367) with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 08:53:34.053] alainbryden/daemon.js: Info: Restarting another 'alainbryden/daemon.js' instance running on home (pid: 23 args: [--disable-script, /alainbryden/work-for-factions.js]) with new args ([--disable-script, /alainbryden/work-for-factions.js])...
[2023-07-13 08:53:34.053] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:34.053] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:35.053] alainbryden/stats.js: WARNING: You cannot start multiple versions of this script (alainbryden/stats.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:35.053] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:36.053] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:36.053] alainbryden/gangs.js: WARNING: You cannot start multiple versions of this script (alainbryden/gangs.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:36.053] alainbryden/bladeburner.js: WARNING: You cannot start multiple versions of this script (alainbryden/bladeburner.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:44.053] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 672) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 08:53:44.053] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 673) with args: []
[2023-07-13 08:53:44.053] alainbryden/autopilot.js: INFO: Launched daemon.js (pid: 674) with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 08:53:44.053] alainbryden/daemon.js: Info: Restarting another 'alainbryden/daemon.js' instance running on home (pid: 367 args: [--disable-script, /alainbryden/work-for-factions.js]) with new args ([--disable-script, /alainbryden/work-for-factions.js])...
[2023-07-13 08:53:44.053] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:44.053] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:45.053] alainbryden/stats.js: WARNING: You cannot start multiple versions of this script (alainbryden/stats.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:45.053] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:46.053] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:46.053] alainbryden/gangs.js: WARNING: You cannot start multiple versions of this script (alainbryden/gangs.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:46.053] alainbryden/bladeburner.js: WARNING: You cannot start multiple versions of this script (alainbryden/bladeburner.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:54.053] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 979) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 08:53:54.053] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 980) with args: []
[2023-07-13 08:53:54.053] alainbryden/autopilot.js: INFO: Launched daemon.js (pid: 981) with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 08:53:54.053] alainbryden/daemon.js: Info: Restarting another 'alainbryden/daemon.js' instance running on home (pid: 674 args: [--disable-script, /alainbryden/work-for-factions.js]) with new args ([--disable-script, /alainbryden/work-for-factions.js])...
[2023-07-13 08:53:54.053] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:54.053] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:55.053] alainbryden/stats.js: WARNING: You cannot start multiple versions of this script (alainbryden/stats.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:55.053] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:56.053] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:56.053] alainbryden/gangs.js: WARNING: You cannot start multiple versions of this script (alainbryden/gangs.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:53:56.053] alainbryden/bladeburner.js: WARNING: You cannot start multiple versions of this script (alainbryden/bladeburner.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:04.054] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 1286) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 08:54:04.054] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 1287) with args: []
[2023-07-13 08:54:04.054] alainbryden/autopilot.js: INFO: Launched daemon.js (pid: 1288) with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 08:54:04.054] alainbryden/daemon.js: Info: Restarting another 'alainbryden/daemon.js' instance running on home (pid: 981 args: [--disable-script, /alainbryden/work-for-factions.js]) with new args ([--disable-script, /alainbryden/work-for-factions.js])...
[2023-07-13 08:54:04.054] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:04.054] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:05.054] alainbryden/stats.js: WARNING: You cannot start multiple versions of this script (alainbryden/stats.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:05.054] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:06.054] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:06.054] alainbryden/gangs.js: WARNING: You cannot start multiple versions of this script (alainbryden/gangs.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:06.054] alainbryden/bladeburner.js: WARNING: You cannot start multiple versions of this script (alainbryden/bladeburner.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:14.054] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 1593) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 08:54:14.054] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 1594) with args: []
[2023-07-13 08:54:14.054] alainbryden/autopilot.js: INFO: Launched daemon.js (pid: 1595) with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 08:54:14.054] alainbryden/daemon.js: Info: Restarting another 'alainbryden/daemon.js' instance running on home (pid: 1288 args: [--disable-script, /alainbryden/work-for-factions.js]) with new args ([--disable-script, /alainbryden/work-for-factions.js])...
[2023-07-13 08:54:14.054] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:14.054] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:15.054] alainbryden/stats.js: WARNING: You cannot start multiple versions of this script (alainbryden/stats.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:15.054] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:16.054] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:16.054] alainbryden/gangs.js: WARNING: You cannot start multiple versions of this script (alainbryden/gangs.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:17.054] alainbryden/bladeburner.js: WARNING: You cannot start multiple versions of this script (alainbryden/bladeburner.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:24.054] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 1900) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 08:54:24.054] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 1901) with args: []
[2023-07-13 08:54:24.054] alainbryden/autopilot.js: INFO: Launched daemon.js (pid: 1902) with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 08:54:24.054] alainbryden/daemon.js: Info: Restarting another 'alainbryden/daemon.js' instance running on home (pid: 1595 args: [--disable-script, /alainbryden/work-for-factions.js]) with new args ([--disable-script, /alainbryden/work-for-factions.js])...
[2023-07-13 08:54:24.054] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:24.054] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:25.054] alainbryden/stats.js: WARNING: You cannot start multiple versions of this script (alainbryden/stats.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:25.054] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:26.054] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:26.054] alainbryden/gangs.js: WARNING: You cannot start multiple versions of this script (alainbryden/gangs.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:27.054] alainbryden/bladeburner.js: WARNING: You cannot start multiple versions of this script (alainbryden/bladeburner.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:34.054] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 2200) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 08:54:34.054] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 2201) with args: []
[2023-07-13 08:54:34.054] alainbryden/autopilot.js: INFO: Launched daemon.js (pid: 2202) with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 08:54:34.054] alainbryden/daemon.js: Info: Restarting another 'alainbryden/daemon.js' instance running on home (pid: 1902 args: [--disable-script, /alainbryden/work-for-factions.js]) with new args ([--disable-script, /alainbryden/work-for-factions.js])...
[2023-07-13 08:54:34.054] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:34.054] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:35.054] alainbryden/stats.js: WARNING: You cannot start multiple versions of this script (alainbryden/stats.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:35.054] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:36.054] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:36.054] alainbryden/gangs.js: WARNING: You cannot start multiple versions of this script (alainbryden/gangs.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 08:54:37.054] alainbryden/bladeburner.js: WARNING: You cannot start multiple versions of this script (alainbryden/bladeburner.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[home /]>

**Comment by mubone2003** [comment]
Later on in the terminal output: - ERRORS start flowing in, in addition to the WARNINGS

[2023-07-13 09:00:55.000] alainbryden/daemon.js: Info: Restarting another 'alainbryden/daemon.js' instance running on home (pid: 13569 args: [--disable-script, /alainbryden/work-for-factions.js]) with new args ([--disable-script, /alainbryden/work-for-factions.js])...
[2023-07-13 09:00:57.000] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:00:58.000] alainbryden/stats.js: WARNING: You cannot start multiple versions of this script (alainbryden/stats.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:00:58.000] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:02.001] alainbryden/bladeburner.js: WARNING: You cannot start multiple versions of this script (alainbryden/bladeburner.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:05.001] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 14087) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 09:01:05.001] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 14088) with args: []
[2023-07-13 09:01:05.001] alainbryden/autopilot.js: ERROR: Failed to launch daemon.js with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 09:01:05.001] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:05.001] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:15.001] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 14364) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 09:01:15.001] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 14365) with args: []
[2023-07-13 09:01:15.001] alainbryden/autopilot.js: ERROR: Failed to launch daemon.js with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 09:01:15.001] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:15.001] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:25.001] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 14641) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 09:01:25.001] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 14642) with args: []
[2023-07-13 09:01:25.001] alainbryden/autopilot.js: INFO: Launched daemon.js (pid: 14643) with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 09:01:25.001] alainbryden/daemon.js: Info: Restarting another 'alainbryden/daemon.js' instance running on home (pid: 13914 args: [--disable-script, /alainbryden/work-for-factions.js]) with new args ([--disable-script, /alainbryden/work-for-factions.js])...
[2023-07-13 09:01:25.001] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:25.001] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:26.001] alainbryden/stats.js: WARNING: You cannot start multiple versions of this script (alainbryden/stats.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:27.001] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:27.001] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:27.001] alainbryden/gangs.js: WARNING: You cannot start multiple versions of this script (alainbryden/gangs.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:28.001] alainbryden/bladeburner.js: WARNING: You cannot start multiple versions of this script (alainbryden/bladeburner.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:32.001] alainbryden/daemon.js: WARNING: daemon.js Caught an error in the targeting loop: Failed to exec /alainbryden/analyze-hack.js on home with 1 threads. This is likely due to having insufficient RAM. Args were: [--all,--silent]
Error: Failed to exec /alainbryden/analyze-hack.js on home with 1 threads. This is likely due to having insufficient RAM. Args were: [--all,--silent]
    at home/alainbryden/daemon.js:532:28
    at autoRetry (home/alainbryden/helpers.js:313:77)
    at async exec (home/alainbryden/daemon.js:529:17)
    at async refreshDynamicServerData (home/alainbryden/daemon.js:845:17)
    at async doTargetingLoop (home/alainbryden/daemon.js:572:17)
    at async Module.main (home/alainbryden/daemon.js:362:5)
    at async N (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1033032)
[2023-07-13 09:01:34.001] alainbryden/faction-manager.js: ERROR: This script requires SF4 (singularity) functions to work.
[2023-07-13 09:01:36.001] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 14794) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 09:01:36.001] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 14795) with args: []
[2023-07-13 09:01:36.001] alainbryden/autopilot.js: ERROR: Failed to launch daemon.js with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 09:01:38.001] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:46.001] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 14919) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 09:01:46.001] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 14920) with args: []
[2023-07-13 09:01:46.001] alainbryden/autopilot.js: ERROR: Failed to launch daemon.js with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 09:01:48.001] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:56.001] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 15180) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 09:01:56.001] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 15181) with args: []
[2023-07-13 09:01:56.001] alainbryden/autopilot.js: ERROR: Failed to launch daemon.js with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 09:01:56.001] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:01:56.001] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:02:03.002] alainbryden/faction-manager.js: ERROR: This script requires SF4 (singularity) functions to work.
[2023-07-13 09:02:05.002] alainbryden/Tasks/backdoor-all-servers.js: Error: The temp script was not run (likely due to insufficient RAM).
  Script:  /Temp/servers-to-backdoor.txt.js
  Args:    ["n00dles","foodnstuff","sigma-cosmetics","joesguns","hong-fang-tea","harakiri-sushi","iron-gym","darkweb","zer0","nectar-net","max-hardware","CSEC","neo-net","phantasy","omega-net","silver-helix","computek","netlink","johnson-ortho","crush-fitness","the-hub","avmnite-02h","summit-uni","syscore","zb-institute","catalyst","rothman-uni","I.I.I.I","millenium-fitness","rho-construction","alpha-ent","aevum-police","lexo-corp","aerocorp","global-pharm","galactic-cyber","snap-fitness","omnia","deltaone","unitalife","defcomm","icarus","univ-energy","solaris","zeus-med","infocomm","taiyang-digital","zb-def","nova-med","titan-labs","microdyne","applied-energetics","run4theh111z","fulcrumtech","stormtech","vitalife","helios","kuai-gong",".","omnitek","4sigma","b-and-a","blade","nwo","clarkinc","powerhouse-fitness","megacorp","The-Cave","ecorp","fulcrumassets"]
  Command: let r;try{r=JSON.stringify(
    ns.args.filter(s => !ns.getServer(s).backdoorInstalled)
);}catch(e){r="ERROR: "+(typeof e=='string'?e:e.message||JSON.stringify(e));}
const f="/Temp/servers-to-backdoor.txt"; if(ns.read(f)!==r) ns.write(f,r,'w')
The script that ran this will likely recover and try again later once you have more free ram.
[2023-07-13 09:02:07.002] alainbryden/autopilot.js: INFO: Launched stockmaster.js (pid: 15347) with args: [--fracH, 0.1, --reserve, 0]
[2023-07-13 09:02:07.002] alainbryden/autopilot.js: INFO: Launched sleeve.js (pid: 15348) with args: []
[2023-07-13 09:02:07.002] alainbryden/autopilot.js: ERROR: Failed to launch daemon.js with args: [--disable-script, /alainbryden/work-for-factions.js]
[2023-07-13 09:02:07.002] alainbryden/stockmaster.js: WARNING: You cannot start multiple versions of this script (alainbryden/stockmaster.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)
[2023-07-13 09:02:07.002] alainbryden/sleeve.js: WARNING: You cannot start multiple versions of this script (alainbryden/sleeve.js). Please shut down the other instance first. (To help with this, a tail window for the other instance will be opened)

**Comment by mubone2003** [comment]
This was not a coding issue. Think this was caused by duplicate copies of files in different directories, including root. Removed all files from this pull from all directories, pulled again, and it has been running fine. Should've caught that before opening an issue.
