### ISSUE TITLE
Repeating warning with Bitburner v2.5.2

### ISSUE THREAD

**Issue by jediknight112** [alainbryden/bitburner-scripts#331]
Not able to pull up Discord so thought i would post it here. I am getting this Warning constantly which is making the terminal very difficult to work with

```
daemon.js: WARNING: daemon.js Caught an error in the targeting loop: 
ns.read('/Temp/singularity-getCurrentWork.txt') returned a bad result: "ERROR: API ACCESS ERROR
Temp/singularity-getCurrentWork.txt.js@home (PID - 21441)

singularity.getCurrentWork: This singularity function requires Source-File 4 to run. A power up you obtain later in the game.
      It will be very obvious when and how you can obtain it.

Stack:
Temp/singularity-getCurrentWork.txt.js:L2@Module.main".
  Script:  /Temp/singularity-getCurrentWork.txt.js
  Args:    []
  Command: ns.singularity.getCurrentWork()
The script was likely passed invalid arguments. Please post a screenshot of this error on discord.
Error: 
ns.read('/Temp/singularity-getCurrentWork.txt') returned a bad result: "ERROR: API ACCESS ERROR
Temp/singularity-getCurrentWork.txt.js@home (PID - 21441)

singularity.getCurrentWork: This singularity function requires Source-File 4 to run. A power up you obtain later in the game.
      It will be very obvious when and how you can obtain it.

Stack:
Temp/singularity-getCurrentWork.txt.js:L2@Module.main".
  Script:  /Temp/singularity-getCurrentWork.txt.js
  Args:    []
  Command: ns.singularity.getCurrentWork()
The script was likely passed invalid arguments. Please post a screenshot of this error on discord.
    at asError (home/helpers.js:325:45)
    at autoRetry (home/helpers.js:339:23)
    at async getNsDataThroughFile_Custom (home/helpers.js:196:22)
    at async getNsDataThroughFile (home/daemon.js:1847:12)
    at async getCurrentWorkInfo (home/daemon.js:158:13)
    at async doTargetingLoop (home/daemon.js:759:32)
    at async Module.main (home/daemon.js:371:5)
    at async L (file:///Users/jeffrey.crane/Library/Application%20Support/Steam/steamapps/common/Bitburner/bitburner.app/Contents/Resources/app/dist/main.bundle.js:2:1084850)
```

**Comment by alainbryden** [comment]
Thanks for reporting the error. The community developing the game
occasionally changes behaviour in ways that subverts these old scripts.

If it was an unintended change, they may opt to revert it in a future
update, otherwise someone will hopefully make a pull request to adapt to
the change. If this remains a problem for a while, I might even get around
to fixing it myself! (although I've been done this game for a while)

**Comment by jediknight112** [comment]
looks like using the `--no-share` arg is a good temp fix:
```
run daemon.js --no-share
```

**Comment by LeDeliJelly** [comment]
I am also getting the same error :/

**Comment by LeDeliJelly** [comment]
> looks like using the `--no-share` arg is a good temp fix:
> 
> ```
> run daemon.js --no-share
> ```

hacking also seems to not work at all and "misfires"

**Comment by NewToScriptin** [comment]
same here

**Comment by NewToScriptin** [comment]
how wouldi remove the share messages entierly
