### ISSUE TITLE
daemon.js not running (question)

### ISSUE THREAD

**Issue by 444knuffelmac** [alainbryden/bitburner-scripts#365]
when trying to run daemon.js i get this error:

RUNTIME ERROR
daemon.js@home (PID - 15979)

Failed to exec analyze-hack.js on home with 1 threads. This is likely due to having insufficient RAM. Args were: [--all,--silent]
stack:
Error: Failed to exec analyze-hack.js on home with 1 threads. This is likely due to having insufficient RAM. Args were: [--all,--silent]
    at home/daemon.js:559:28
    at autoRetry (home/helpers.js:379:86)
    at async exec (home/daemon.js:556:17)
    at async refreshDynamicServerData (home/daemon.js:868:17)
    at async getStaticServerData (home/daemon.js:857:5)
    at async main (home/daemon.js:370:5)
    at async R (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:9:401629)

my question is, is tihs my computers ram, or in game ram? (i have 4tb in game ram (like 10gb max used), and 32gb irl (around15gb usable))

**Comment by alainbryden** [comment]
I recently fixed some situations where home reserved ram would be violated, so hopefully this is all that was.
