### ISSUE TITLE
scan.js seems broken after b903489 without --hide-stats

### ISSUE THREAD

**Issue by trcjr** [alainbryden/bitburner-scripts#402]
`run scan.js`

```
RUNTIME ERROR
scan.js@home (PID - 21176)

Cannot read properties of undefined (reading 'toFixed')
stack:
TypeError: Cannot read properties of undefined (reading 'toFixed')
    at formatNumber (home/helpers.js:45:35)
    at createServerEntry (home/scan.js:73:29)
    at buildOutput (home/scan.js:79:44)
    at buildOutput (home/scan.js:94:27)
    at main (home/scan.js:127:51)
    at R (file:///Users/trcjr/Library/Application%20Support/Steam/steamapps/common/Bitburner/bitburner.app/Contents/Resources/app/dist/main.bundle.js:9:401635)
```

**Comment by alainbryden** [comment]
Weird, one of your servers must be returning undefined for a value that was
always there on my game.

Could you possibly upload your save so I can see what it is?

Cheers

**Comment by trcjr** [comment]
[bitburnerSave_1729772363_BN12x21.json.gz](https://github.com/user-attachments/files/17506722/bitburnerSave_1729772363_BN12x21.json.gz)

**Comment by alainbryden** [comment]
Thanks for the save. All my testing had been done without hacknet servers, which apparently have many undefined values. Should all be fixed now.
