### ISSUE TITLE
daemon.js: tail is not defined when run by autopilot.js

### ISSUE THREAD

**Issue by FIM43-Redeye** [alainbryden/bitburner-scripts#410]
WARN: daemon.js Caught an error during startup:   ReferenceError: tail is not defined
        at tryRunTool (home/daemon.js:591:13)
        at async runStartupScripts (home/daemon.js:529:33)
        at async startup (home/daemon.js:433:9)
        at async main (home/daemon.js:221:13)
        at async R 
daemon.js: WARNING: daemon.js Caught an error in the targeting loop:   ReferenceError: tail is not defined
        at tryRunTool (home/daemon.js:591:13)
        at async runStartupScripts (home/daemon.js:529:33)
        at async doTargetingLoop (home/daemon.js:677:61)
        at async startup (home/daemon.js:439:5)
        at async main (home/daemon.js:221:13)
        at async R 

This happens repeatedly, and each time it tries to start new copies of the respective script.

**Comment by alainbryden** [comment]
Pushed a bad commit earlier, thus is fixed now. Thanks for reporting and sorry for the bother.
